home_page: "https://www.stryker.com/us/en/index.html"
contact_page_title: "Contact | Stryker"
pages_info_sheet_name: 'PagesInfo'

# --API--
API.base.URI: "https://api.predic8.de/shop/v2"
#each user type
#userName= info
#password=info

# --DB_CONNECTION_STRING--
dbURL: ""
dbUsername: ""
dbPassword: ""
#each user type
#userName= info
#password=info